### ISSUE TITLE
Live reload

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#1653]
- [x] AZLE_AUTORELOAD=true
- [x] give warning if deploying to network ic and that environment variable is set
- [x] we need the agent installed at the azle level for the file watcher, this is a major bug
- [x] if podman still doesn't work on mac
  - [x] try combinations of changing the hypervisor, the queme thing, brew update, brew upgrade, etc
  - [x] In the worst case let's just deploy it as it is and prepare documentation for Mac to solve these issues
  - [x] keep this in mind https://github.com/containers/podman/issues/20776
  - [x] There's also the issue of the virtual machine taking forever to load and a long time on each azle deploy for some reason...it's like it is really really slow, I don't know if Docker will be better. Maybe with autoreload the experience will be just fine
- [x] On Ubuntu and mac we might want to tell them to do update and upgrade
- [x] make sure to run tests for 0.20.2 on Mac
  - [x] Should we force those tests to use curl? Right now we are only testing building the image locally, and I have one failure so far
- [x] the github actions cache is now wrong I think, it would need to hash the rust directory too right?
- [x] we can't just watch the entire directory...otherwise we will potentially have reloads for everything, for example imagine a frontend app with .ts or .js files, if you edit them the azle canister will reload: https://github.com/demergent-labs/azle/issues/1664
- [x] create a security section for azle canisters
- [x] if we don't get assets to work, explain that
- [x] document how to develop in Rust with the hash and stuff
- [x] update documentation to show the environment variable when deploying
- [x] what about assets?
- [x] Get good logging, use AZLE_VERBOSE probably
- [x] write a test for this, just write to a file to change it and run the test again without a dfx deploy
- [x] we need to be able to lock things down...for each attempt we have to let that attempt finish
  - [x] maybe create an id and queue system
- [x] put in warning if deploying with auto_reload true
- [x] add the npx azle kill-autoreload command: https://github.com/demergent-labs/azle/issues/1661
