### ISSUE TITLE
Tracking down Prop Test Errors

### ISSUE THREAD

**Issue by bdemann** [demergent-labs/azle#1736]
## Method
I am going through all of the actions, starting at those running today and going back until I get tired or I get to the last time there was a pr affecting property tests, with the assumption being that any actions before that would have been looked at to try and figure out why they were failing. I am ignoring actions where a large number of actions failed preferring ones were only one or two actions failed; I am assuming that actions where lots of things were failing had critical issues that were addressed and that those critical issues probably covered up any problems with the property tests. I am also ignoring stable_b_tree_map prop tests. I am only looking at other prop tests.

On Feb 15 https://github.com/demergent-labs/azle/commit/6eaa4b149fcb1234e18e78e81f5defb8178ca2fe was merged in which was a significant fix to the http_request prop tests. So I am not going to look further back than Feb 15.

### Ok or Err errors

What we are looking at here is the canister rust code being generated like this
```rust
#[export_name = "canister_query Err"]
fn __canister_method_Err() {
    ic_cdk::setup();
    ic_cdk::spawn(async {
        let () = ic_cdk::api::call::arg_data();
        let result = Err();
    });
}
fn Err() {
    execute_js("Err", true);
}
```

From this code

```rust
let rust_function_name = canister_method.name.to_ident();
let js_function_name = &canister_method.name;
...
quote! {
    #[ic_cdk_macros::query(manual_reply = true, composite = #is_composite #guard_attribute)]
    fn #rust_function_name() {
        execute_js(#js_function_name, true);
    }
```

Our code does no sanitation on the canister method name so what you put in there is going to just show up in the generated rust code. For the rest of the rust keywords we have them filtered out of our property tests. Which indicates to me that we are going with a "inform the developers that all of the rust keywords are reserved approach." I will follow suit here.

- [x] error[E0532]: expected tuple struct or tuple variant, found function `Ok`
     - Found in: https://github.com/demergent-labs/azle/actions/runs/8546232133/job/23416246975?pr=1732
     - Prop test: Record
     - Caused by having a query/update method called 'Ok'
     - Questions
          - Why is that breaking?
          - After we know that we can determine if we want to make that a reserved word or if we want to fix the issue.
- [x] error[E0532]: expected tuple struct or tuple variant, found function `Ok`
     - Found in: https://github.com/demergent-labs/azle/actions/runs/8457454101/
     - Prop test: text
     - Probably the same as the one above
- [x] error[E0532]: expected tuple struct or tuple variant, found function `Ok`
     - Found in: https://github.com/demergent-labs/azle/actions/runs/8454483796
     - Prop test: Record
     - Probably the same as the one above
- [x] error[E0532]: expected tuple struct or tuple variant, found function `Err`
     - Found in: https://github.com/demergent-labs/azle/actions/runs/8443362969/
     - Prop test: text
     - Probably the same as the one above but with a method called Err
- [x] error[E0532]: expected tuple struct or tuple variant, found function `Ok`
     - Found in: https://github.com/demergent-labs/azle/actions/runs/8380933992
     - Prop test: int8
     - Probably the same as the one above
- [x] error[E0532]: expected tuple struct or tuple variant, found function `Ok`
     - Found in: https://github.com/demergent-labs/azle/actions/runs/8366353900/
     - Prop test: blob
     - Probably the same as the one above
- [x] error[E0532]: expected tuple struct or tuple variant, found function `Ok`
     - Found in: https://github.com/demergent-labs/azle/actions/runs/8351062304
     - Prop test: principal
     - Probably the same one as above

### Http Errors
- [x] This comparison appears to be unintentional because the types '"~^$'**m$ |`~"' and '"$$"' have no overlap.
     - Found in: https://github.com/demergent-labs/azle/actions/runs/8475100819
     - Prop test: http_request
     - The problem was actually the name of the header, one was "j" and the other was "J" and due to some case insensitivity they both became the same header "j". Hopefully all of the other errors are the same issue.
- [x] This comparison appears to be unintentional because the types '".`"' and '"|_#^|.^#*to"' have no overlap.
    - Found in: https://github.com/demergent-labs/azle/actions/runs/8335053798
    - Prop test: http_request
    - Probably the same as the other http_request issue above
    - 'g' and 'G'
- [x] This comparison appears to be unintentional because the types '"R~'~`V"' and '"l2"' have no overlap.
    - Found in: https://github.com/demergent-labs/azle/actions/runs/8334765292
    - Prop test: http_request
    - Probably the same as the other http_request issue above
    - 'c' and 'C'
- [x] This comparison appears to be unintentional because the types '"|'|w%*"' and '"%"' have no overlap.
     - Found in: https://github.com/demergent-labs/azle/actions/runs/8000102526
     - Prop test: http_request
     - Probably the same as the other http_request issue above
     - I was unable to reproduce this, so the shape might have changed to much, but it does look like the same error. Even going back to a commit that happened at this same time yielded the same list of headers that still failed to reproduce this error. I'm going to call it good for right now.

### Disregardable Errors
- [x] rm: cannot remove '/tmp/tmp.knKHviSiuL/dfxvm*': No such file or directory
     - Found in: https://github.com/demergent-labs/azle/actions/runs/8363206323/
     - Prop test: int32
     - looks like some sort of network error, I'm going to disregard it
- [x] error: HTTP status server error (503 Service Unavailable) for url
     - Found in: https://github.com/demergent-labs/azle/actions/runs/8362379253
     - Prop test: principal
     - looks like some sort of network error, I'm going to disregard it
- [x] TypeScript error: The symbol "m2" has already been declared
     - Found in: https://github.com/demergent-labs/azle/actions/runs/7946122836/
     - Prop test: recursive
     - The error has already been addressed and I will disregard all future occurrences of this error
     - The error was caused from importing azle from both relative and absolute paths.
     - The fix was merged February 20th, 2024 12:56 PM and this log is from Feb 17
- [x] test int32 SdAAPe9d2 failed Error: Invalid certificate: Signature verification failed
     - Found in: https://github.com/demergent-labs/azle/actions/runs/7943820108
     - Prop test: int32
- [x] test float32 nL9 failed Error: Invalid certificate: Signature verification failed
     - Found in: https://github.com/demergent-labs/azle/actions/runs/7943820108
     - Prop test: float32
- [x] test opt _wb failed Error: Invalid certificate: Signature verification failed
     - Found in: https://github.com/demergent-labs/azle/actions/runs/7943820108
     - Prop test: opt
- [x] Uncaught ReferenceError: 'Principal' is not defined
     - Found in: https://github.com/demergent-labs/azle/actions/runs/7923600469/
     - Prop test: service
     - This was a bug that was found while testing weird float behavior. It should have been fixed by  adding https://github.com/demergent-labs/azle/commit/eb9b4e57188b0d49eda2152935e73bfbd39bce4a to main

### Cannot find module Errors
All of these errors come from the recursive prop test which was modified Feb 20 and all of these actions failed Feb 17 all as part of the same release candidate. We haven't seen this error since the Feb 20 fix, so I am guessing that if we fire them up now we will not get the error again.

To be sure I reran one with the same seed and was unable to reproduce the error.

To be doubly sure I copied the generated code from the counter example in the test and it still was not reproducible

- [x] test recursive aY752v20L4 failed Error: Cannot find module './tests/recursive/test/dfx_generated/canister/index.js'
     - Found in: https://github.com/demergent-labs/azle/actions/runs/7946657718
     - Prop test: recursive
     - Merge from release 0.20.0 Feb 17
- [x] test recursive _e failed Error: Cannot find module './tests/recursive/test/dfx_generated/canister/index.js'
     - Found in: https://github.com/demergent-labs/azle/actions/runs/7946364656
     - Prop test: recursive
     - release 0.20.0 Feb 17
- [x] test recursive _B4 failed Error: Cannot find module './tests/recursive/test/dfx_generated/canister/index.js'
     - Found in: https://github.com/demergent-labs/azle/actions/runs/7945441276
     - Prop test: recursive
     - release 0.20.0-rc.16 Feb 17
 - [x] test recursive EnksLytF failed Error: Cannot find module './tests/recursive/test/dfx_generated/canister/index.js'
     - Found in: https://github.com/demergent-labs/azle/actions/runs/7943300554
     - Prop test: recursive
     - release 0.20.0-rc.15 Feb 17

### Misc
- [x] Uncaught Error: Unexpected value for header '__proto__'. Expected 'constructor' but received '[object Object]'
     - Found in: https://github.com/demergent-labs/azle/actions/runs/7943300554
     - Prop test: http_request
     - Unable to reproduce (this error occured on Feb 17 and there were updates to prop tests Feb 20)
- [x] Error: Failed while trying to deploy canisters.
     - Found in: https://github.com/demergent-labs/azle/actions/runs/7938299347
     - Prop test: principal
     - unable to reproduce
