### ISSUE TITLE
Azle 0.24.0

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#1922]
# Tasks

- [x] Should we create our own tsconfig for esbuild? Or should we ask it to read the tsconfig.json of the dev? In some ways it would be really nice to keep it standard...but it would also be nice for them to config...not sure...I am leaning towards having our own standard tsconfig settings because we really need tight control on the Azle environment...but then again, the goal should probably be to make that not matter
- [x] Is there any way to get rid of `npx azle` and have something that will definitely go to the nearest node_modules directory and grab the correct executable from bin?
- [x] install_script.sh needs a shebang at the top
- [x] https://github.com/demergent-labs/azle/issues/1919
- [x] change timers to use not a global variable but class instance
- [x] should we change all of the class syntax to use class variables?
- [x] No more intermittent tests!
- [x] We should write tests for azle chunk
- [x] set_outgoing_http_options should not be in stable
- [x] make sure all did files are truly gone from all examples if they shouldn't be there
- [x] is azle template a good command name?
- [x] Should we change AZLE_GEN_WASM=true to AZLE_TEMPLATE=true?
- [x] fetch is another global that we need to make unusable if not in experimental mode...any others?
- [x] Major issue with this and class api if experimental is enabled, this is not defined
- [x] new test should be inside of http_server under tests...we should change the names of new, hello world, etc to match what they are, candid_rpc, http_server, etc
- [x] manually test the new commands
- [x] Azle ic-cdk ensure correct updates in cargo.lock in azle and kybra
- [x] Update kybra and release it
- [x] Get new release process working
- [x] Make sure that the release tests test everything using the AZLE_TEST_RUN_ON_RELEASE env var
- [x] what happened to @dfinity/agent in the package.json of our tests?
- [x] We need to compile and commit the wasm binaries
- [x] do an audit fix, we need to update ethers and get it working well
- [x] Make an issue: should setInterval, clearTimeout be stable?
- [x] are we going to get rid of the canister path azle/canister and just do generated types?
- [x] Make an issue...we need to run all stable syntax tests with the experimental flag as well, because stable syntax needs to work well even if the experimental flag is set. I'm dealing with a nasty class context (this) issue right now that only came up during manual testing
- [x] Play with the new stable memory file system personally, check out the code and stuff personally
- [x] update to dfx 0.22.0

# Features
- [x] stable memory file system (memory id 254 is now reserved, we need to document this)
- [x] experimental flag in dfx.json for azle/experimental and Nodejs APIs

# Breaking Changes
- [x] file system is no longer in memory but in stable memory
- [x] If the experimental flag is not set, there will be a runtime error when using experimental features
- [x] only AZLE_VERBOSE works now, --verbose and -v have been removed
- [x] all custom Azle properties in dfx.json are moved into the custom property, besides custom itself
- [x] npx azle new [name] --http-server must now have the --experimental flag
- [x] AZLE_WASMEDGE_QUICKJS_DIR changed to AZLE_WASMEDGE_QUICKJS_PATH...actually the environment variable is entirely gone
- [x] Running npx azle install-dfx-extension is no longer necessary...devs must run npm install (or npm install azle) before starting up a replica in the same directory as their package.json file
- [x] node_modules/.bin/azle is now used instead of npx azle for commands...might need to update documentation
- [x] azle compile [canister name] is now used instead of azle [canister name]
- [x] npx is no longer used, node_modules/.bin/azle
- [x] wasm binary optimization no longer exists
