### ISSUE TITLE
Work on test stabilization

### ISSUE THREAD

**Issue by bdemann** [demergent-labs/azle#2017]
## Main Goal
- [x] Make test.yml pristine https://github.com/demergent-labs/azle/issues/2023
- [x] Enumerate fragile tests https://github.com/demergent-labs/azle/issues/1998
- [x] Enumerate long running tests https://github.com/demergent-labs/azle/issues/2026
