### ISSUE TITLE
Waiting on cross-canister calls

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#31]
- [x] Clean up the compiler code
  - [x] Make IC type work correctly: https://github.com/demergent-labs/azle/issues/39
  - [x] Clean up file structure: https://github.com/demergent-labs/azle/issues/40
  - [x] Clean up individual files: https://github.com/demergent-labs/azle/issues/40
  - [x] No TypeScript errors
- [x] Add candid compiler (generator at least is complete for now, TypeScript -> Candid compiler will probably be coming soon)
  - [x] Candid compiler has some issues with multiple commas
- [x] Use Rust -> Candid or Candid -> Rust compiler...I don't remember which compiler I am going to use but use it: https://github.com/demergent-labs/azle/issues/32
- [x] Add imports
- [x] Add swc support to provide hopefully all ECMAScript features
- [x] Open boa issue for += and such operators (this may be fixed now, try running broken examples again)
- [x] Create pull request to boa for randomness
- [x] Add date capabilities
- [x] Start writing examples
- [x] Implement all synchronous APIs
- [x] Fix error reporting, we need nice succinct errors not the huge globby mess
- [x] Use boa upstream, because a lot of issues have actually been solved
- [x] Use official conversions from and to JsValue instead of the hacky stringification I am doing: https://github.com/boa-dev/boa/pull/1851
- [x] spack and imports
  - [x] Apparently spack is breaking when trying to import from node_modules, it won't parse TypeScript files and I might run into issues where it won't bundle other imports if they are from node_modules
- [x] I am going to try out esbuild, seems like spack might not be ready for prime-time
- [x] Create better documentation
- [x] Start creating video series
- [x] Fix double-quote problem
- [x] Int, i128, i64, Nat, u128, and u64 are not fully representable in JS. We will probably need to use some kind of BigInt or string representation to get this to work...I suggest we use an automatic BigInt representation for all special number types...this might be the best way to do it
- [x] Add float32 and float64...
- [x] Experiment with async code since I am compiling to ES3
- [x] Do we allow for any kind of optional types on the function parameters or return types?
- [x] I think cross-canister calls might be possible using ic_cdk::spawn and callbacks
- [x] Add project-wide TypeScript check
