### ISSUE TITLE
0.5.0 launch checklist

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#553]
- [x] Make sure NOTICEs are in all examples
- [x] Check licensing for all code examples
- [x] Fix Candid explanation, explanation of where you need to use TypeScript (or just remove it)
- [x] Create release notes
  - [x] Clean them up, nice list of all new features, especially highlight breaking changes
  - [x] breaking changes
    - [x] stableStorage to stable_storage
    - [x] canisterBalance to canister_balance
- [x] Tweet
- [x] Explain that inline types should not be used or should be avoided, everything should be given a type alias...also explain that the * import syntax should not be used
- [x] Fix array enclosed type phrasing
- [x] Fix Variant example field names, make them upper case camel case
- [x] data certificate comment is wrong 
- [x] remove rejectioncode import from call example
- [x] call raw example should be a generator 
- [x] msg cycles accept 128 should return a nat
- [x] remove rejectioncode import from reject message
 - [x] stable size return type is wrong
