### ISSUE TITLE
Azle Compiler Redesign

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#629]
- [x] No more TypeScript to Candid
- [x] No more Candid to Rust
- [x] Generate all Rust data types from the TypeScript code
- [x] Create function bodies with parameters and return type
- [x] Follow each parameter and create all referenced Structs and Enums, including all inlined types
- [x] Follow the return type and create all referenced Structs and Enums, including all inlined types
- [x] Hook in JS function bodies: https://github.com/demergent-labs/azle/issues/634
- [x] Hook in IC object with all functionality: https://github.com/demergent-labs/azle/issues/640
- [x] Variants are blocking a lot of things
- [x] Hook in all system methods
  - [x] init: https://github.com/demergent-labs/azle/issues/647
  - [x] pre_upgrade: https://github.com/demergent-labs/azle/issues/648
  - [x] post_upgrade: https://github.com/demergent-labs/azle/issues/649
  - [x] heartbeat: https://github.com/demergent-labs/azle/issues/642
  - [x] inspect message: https://github.com/demergent-labs/azle/issues/643
- [x] stable storage: https://github.com/demergent-labs/azle/issues/654
- [x] generators: https://github.com/demergent-labs/azle/issues/662
- [x] cross canister calls: https://github.com/demergent-labs/azle/issues/664
- [x] Query/Update functions: https://github.com/demergent-labs/azle/issues/632
- [x] All IC object functionality
- [x] Restore all variants in example tests: https://github.com/demergent-labs/azle/issues/650
- [x] QueryManual and UpdateManual: https://github.com/demergent-labs/azle/issues/665
- [x] Make sure we can handle void return types in the method body
- [x] manual_reply example has incorrect record names in the generated Candid. Opened issue `https://github.com/dfinity/candid/issues/375`
- [x] inline types: https://github.com/demergent-labs/azle/issues/670
- [x] tuple types: https://github.com/demergent-labs/azle/issues/669

## Tests
- [x] bytes
- [x] call_raw
- [x] candid_encoding
- [x] complex_types
- [x] counter
- [x] cross_canister_calls
- [x] cycles
- [x] date
- [x] ethereum_json_rpc
- [x] func_types
- [x] generators
- [x] heartbeat
- [x] ic_api
- [x] imports
- [x] init
- [x] inline_types (waiting on full implementation)
- [x] inspect_message
- [x] key_value_store
- [x] ledger_canister (hopefully broken because of incomplete inline_types implementation)
- [x] management_canister
- [x] manual_reply
- [x] motoko_examples
  - [x] calc
  - [x] counter
  - [x] echo
  - [x] factorial
  - [x] hello
  - [x] hello-world
  - [x] http_counter (needs tuples)
  - [x] minimal-counter-dapp
  - [x] persistent-storage
  - [x] phone-book
  - [x] quicksort
  - [x] simple-to-do
  - [x] superheroes (panicked at not yet implemented, needs tuple types and might need to get rid of ? in Superhero type)
  - [x] whoami
- [x] notify_raw
- [x] null_example
- [x] optional_types
- [x] outgoing_http_requests
- [x] pre_and_post_upgrade
- [x] primitive_types
- [x] principal
- [x] query
- [x] rejections
- [x] simple_erc20
- [x] simple_user_accounts
- [x] stable_memory
- [x] stable_storage
- [x] tuple_types (needs to be implemented)
- [x] update

**Comment by dansteren** [comment]
Just checked the last box. There are some sub-issues that have unchecked things but by and large this is completed so I'm closing it out.
