### ISSUE TITLE
Epic | Azle Compiler Refactor

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#674]
- [x] Directory and file structure refactor
  - [x] Consolidate getters into ts_ast dir https://github.com/demergent-labs/azle/issues/675
  - [x] System canister methods should be pulled up a dir (we're reconsidering this)  - https://github.com/demergent-labs/azle/issues/690
  - [x] Variant and records are pulled up a dir https://github.com/demergent-labs/azle/issues/681
- [x] Remove stale code - https://github.com/demergent-labs/azle/pull/679
  - [x] Macro crate
  - [x] TS to Candid
  - [x] Candid to Rust Types
  - [x] TS to Rust
  - [x] Rename typescript_to_rust_redesign dir to typescript_to_rust
- [x] De-couple CanisterMethods from TsAst references - https://github.com/demergent-labs/azle/pull/687
- [x] De-couple system canister methods - https://github.com/demergent-labs/azle/issues/690
- [x] clean up unused imports/functions from rewrite
- [x] AST Node traits - https://github.com/demergent-labs/azle/issues/697
- [ ] https://github.com/demergent-labs/azle/issues/702

General Architecture:

```plaintext
  TS AST
    ||           .to_act_node()
    \/           
ACT/RustType
    ||          .to_token_string()
    \/
Generators      CanisterMethod.generate(CanisterMethodNode)
    ||
    \/
TokenStreams

Program.to_act_node().to_token_stream()
```
