### ISSUE TITLE
Epic | Compiler Messaging

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#708]
- [x] All Boa errors should panic with a simple string message: https://github.com/demergent-labs/azle/issues/354
- [x] Compiler diagnostics should be clean and concise: https://github.com/demergent-labs/azle/issues/710
  - [x] Debug and production modes (like a verbose flag)
- [x] All Azle compiler errors should guide the user to a fix: https://github.com/demergent-labs/azle/issues/77
- [x] Halt execution in azle.ts when a rust error is encountered: https://github.com/demergent-labs/azle/issues/719
