### ISSUE TITLE
Epic | Stable Structures

### ISSUE THREAD

**Issue by dansteren** [demergent-labs/azle#810]
Get the StableBTreeMap API fully working in Azle. See the comments below for further explanation.

Child Issues
- [x] #833
- [x] #839 
- [x] #848
- [x] #849
- [x] #852 

Relates to demergent-labs/kybra#163

**Comment by lastmjs** [comment]
Ideas for the API in Azle:

```typescript
type User = {
    id: string;
    username: string;
};

let stable_map: StableMap<
    string,
    User,
    {
        max_key: 10;
        max_value: 100;
    }
> = ic.stable_map();
```

```typescript
type User = {
    id: string;
    username: string;
};

let stable_map: StableMap<(string, 10), (User, 100)> = ic.stable_map();
```

**Comment by lastmjs** [comment]
```typescript
import { StableBTreeMap } from 'azle';

type User = {
  id: string;
  username: string;
};

let stable_map<string, User> = StableBTreeMap('stable_map', 10, 100);
```

**Comment by lastmjs** [comment]
Some ramblings:

```typescript
class StableBTreeMap<K, V> {
    constructor(var_name: string, key_size: number, value_size: number) {}

    get(key: K): V {}

    insert(key: K, value: V): K {}
}

// function StableBTreeMap<K, V>(
//     var_name: string,
//     key_size: number,
//     value_size: number
// ) {}

// type StableBTreeMap<K, V> = {
//     get(key: K): V;
//     insert(key: K, value: V): K;
// };

let stable_map = new StableBTreeMap<string, number>('0', 10, 1000);

let result = stable_map.get('0');
let key = stable_map.insert('1', 32342);
```

**Comment by lastmjs** [comment]
```rust
pub struct StableBTreeMapNode {
    pub memory_id: u8,
    pub key_type: proc_macro2::TokenStream,
    pub value_type: proc_macro2::TokenStream,
    pub max_key_size: u32,
    pub max_value_size: u32,
}
```

**Comment by lastmjs** [comment]
Remaining items:

- [ ] Parsing for primitives
- [ ] Runtime for primitives
- [ ] Parsing for lists
- [ ] Runtime for lists
- [ ] Parsing for records
- [ ] Runtime for records
- [ ] Parsing for variants
- [ ] Runtime for variants

**Comment by lastmjs** [comment]
Please add the following APIs that Kybra now has:

- [ ] keys
- [ ] values
- [ ] items

**Comment by dansteren** [comment]
The `keys`, `values`, and `items` methods have been added in #850.
