### ISSUE TITLE
TypeScript -> Candid compiler implement func

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/azle#86]
Skipped for the time being, when it becomes important let's implement it. I think other things have a higher priority currently.

- [x] Compile to Candid
- [x] AzleIntoJsValue
- [x] AzleTryFromJsValue
- [x] Derives
  - [x] AzleIntoJsValue
    - [x] Enum
    - [x] Struct
  - [x] AzleTryFromJsValue
    - [x] Enum
    - [x] Struct
- [x] Make sure records and variants can have funcs...funcs should be usable everywhere
- [x] Canister definitions
  - [x] More tests would be desirable
- [x] Stable storage
  - [x] More tests would be desirable
- [x] Should we put the param names in the definition or not? Candid seems to allow both (will handle later here: https://github.com/demergent-labs/azle/issues/441)
- [x] query annotation (does this matter??)
- [x] oneway annotation?
- [x] inline funcs (will handle later here: https://github.com/demergent-labs/azle/issues/416)
- [x] Add func functionality to ledger canister with tests
- [x] Test out the asset canister if possible...or make sure Azle can interoperate with it, it has a func type with the streaming callback
- [x] Finish up tests once this is resolved: https://github.com/dfinity/candid/issues/348
- [x] allow arrays of funcs...allow arrays of everything

**Comment by cryptoisgood** [comment]
I think we need this in order to implement `http_request` unless I'm misunderstanding my issues, but it's related to [this](https://github.com/demergent-labs/azle/issues/192). I'm going to keep working on this see if I can figure it out.
